{
  "threat_severity": "Moderate",
  "public_date": "2020-01-03T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-5313 python-pillow: out-of-bounds read in ImagingFliDecode when loading FLI images",
    "id": "1789532",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1789532"
  },
  "cvss3": {
    "cvss3_base_score": "8.2",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:H",
    "status": "draft"
  },
  "cwe": "CWE-125",
  "details": [
    "libImaging/FliDecode.c in Pillow before 6.2.2 has an FLI buffer overflow.",
    "An out-of-bounds read was discovered in python-pillow in the way it decodes FLI images. An application that uses python-pillow to load untrusted images may be vulnerable to this flaw, which can allow an attacker to read the memory of the application they should be not allowed to read."
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Out of support scope",
      "package_name": "python-imaging",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "python-imaging",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Affected",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Affected",
      "package_name": "quay",
      "cpe": "cpe:/a:redhat:quay:3::el7"
    }
  ],
  "upstream_fix": "python-pillow 6.2.2",
  "name": "CVE-2020-5313"
}
