{
  "threat_severity": "Low",
  "public_date": "2018-09-21T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2018-20406 python: Integer overflow in Modules/_pickle.c allows for memory exhaustion if serializing gigabytes of data",
    "id": "1664509",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1664509"
  },
  "cvss3": {
    "cvss3_base_score": "5.9",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "verified"
  },
  "cwe": "CWE-190->CWE-400",
  "details": [
    "Modules/_pickle.c in Python before 3.7.1 has an integer overflow via a large LONG_BINPUT value that is mishandled during a \"resize to twice the size\" attempt. This issue might cause memory exhaustion, but is only relevant if the pickle format is used for serializing tens or hundreds of gigabytes of data."
  ],
  "statement": "This issue did not affect the versions of python as shipped with Red Hat Enterprise Linux 5, 6 and 7.",
  "affected_release": [
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 6",
      "release_date": "2019-11-06T00:00:00Z",
      "advisory": "RHSA-2019:3725",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3",
      "package": "rh-python36-python-0:3.6.9-2.el6"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7",
      "release_date": "2019-11-06T00:00:00Z",
      "advisory": "RHSA-2019:3725",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3",
      "package": "rh-python36-python-0:3.6.9-2.el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7.5 EUS",
      "release_date": "2019-11-06T00:00:00Z",
      "advisory": "RHSA-2019:3725",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3",
      "package": "rh-python36-python-0:3.6.9-2.el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS",
      "release_date": "2019-11-06T00:00:00Z",
      "advisory": "RHSA-2019:3725",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3",
      "package": "rh-python36-python-0:3.6.9-2.el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7.7 EUS",
      "release_date": "2019-11-06T00:00:00Z",
      "advisory": "RHSA-2019:3725",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3",
      "package": "rh-python36-python-0:3.6.9-2.el7"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Not affected",
      "package_name": "python",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "python",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "python",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "python3",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Will not fix",
      "package_name": "python36",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Will not fix",
      "package_name": "python36:3.6/python36",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "rh-python35-python",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    }
  ],
  "upstream_fix": "python 3.7.1",
  "references": [
    "https://python-security.readthedocs.io/vuln/pickle-load-dos.html"
  ],
  "name": "CVE-2018-20406"
}
