{
  "threat_severity": "Important",
  "public_date": "2020-01-03T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-5311 python-pillow: out-of-bounds write in expandrow in libImaging/SgiRleDecode.c",
    "id": "1789535",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1789535"
  },
  "cvss3": {
    "cvss3_base_score": "9.8",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "status": "verified"
  },
  "cwe": "CWE-787",
  "details": [
    "libImaging/SgiRleDecode.c in Pillow before 6.2.2 has an SGI buffer overflow.",
    "An out-of-bounds write flaw was discovered in python-pillow in the way SGI RLE images are decoded. An application that uses python-pillow to decode untrusted images may be vulnerable to this flaw, which can allow an attacker to crash the application or potentially execute code on the system."
  ],
  "statement": "This issue did not affect the versions of python-pillow and python-imaging as shipped with Red Hat Enterprise Linux 6, and 7 as they did not include the SGI RLE image decoder, where the flaw lies.",
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2020-02-24T00:00:00Z",
      "advisory": "RHSA-2020:0580",
      "cpe": "cpe:/a:redhat:enterprise_linux:8",
      "package": "python-pillow-0:5.1.1-10.el8_1"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8.0 Update Services for SAP Solutions",
      "release_date": "2020-02-20T00:00:00Z",
      "advisory": "RHSA-2020:0566",
      "cpe": "cpe:/a:redhat:rhel_e4s:8.0",
      "package": "python-pillow-0:5.1.1-10.el8_0"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Out of support scope",
      "package_name": "python-imaging",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "python-imaging",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Affected",
      "package_name": "quay",
      "cpe": "cpe:/a:redhat:quay:3::el7"
    }
  ],
  "upstream_fix": "python-pillow 6.2.2",
  "name": "CVE-2020-5311"
}
