{
  "threat_severity": "Low",
  "public_date": "2020-06-25T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-10994 python-pillow: multiple out-of-bounds reads via a crafted JP2 file",
    "id": "1852820",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1852820"
  },
  "cvss3": {
    "cvss3_base_score": "5.3",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
    "status": "draft"
  },
  "cwe": "CWE-125",
  "details": [
    "In libImaging/Jpeg2KDecode.c in Pillow before 7.1.0, there are multiple out-of-bounds reads via a crafted JP2 file."
  ],
  "statement": "This issue did not affect the versions of python-pillow and python-imaging as shipped with Red Hat Enterprise Linux 5, 6, and 7 as they did not include the JP2 image parser, where the flaw lies.",
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Not affected",
      "package_name": "python-imaging",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "python-imaging",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Will not fix",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Affected",
      "package_name": "quay",
      "cpe": "cpe:/a:redhat:quay:3::el7"
    }
  ],
  "upstream_fix": "python-pillow 7.1.0",
  "name": "CVE-2020-10994"
}
